jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.image }}

    steps:
      - checkout: self
        submodules: true

      - task: CmdLine@2
        inputs:
          script: |
            gradle --version
            gradle wrapper
        displayName: "Gradle Wrapper"

      # cpp tasks
      - task: Gradle@2
        inputs:
          options: "-b cpp.gradle"
          jdkVersionOption: "1.11"
          tasks: "codegen"
        displayName: "C++ Codegen"

      - task: Gradle@2
        inputs:
          options: "-b cpp.gradle"
          jdkVersionOption: "1.11"
          jdkArchitectureOption: "x64"
          tasks: "build test"
        displayName: "C++ Build/Test"

      # java tasks
      - task: Gradle@2
        inputs:
          jdkVersionOption: "1.11"
          tasks: "dependencies"
        displayName: "Gradle Tasks"

      - task: Gradle@2
        inputs:
          options: "-b build.gradle"
          jdkVersionOption: "1.11"
          jdkArchitectureOption: "x64"
          tasks: "build"
        displayName: "Java Build"

      - task: Gradle@2
        inputs:
          options: "-b build.gradle"
          jdkVersionOption: "1.11"
          jdkArchitectureOption: "x64"
          tasks: "test"
          publishJUnitResults: true
          testResultsFiles: "build/test-results/test/TEST-*.xml"
        displayName: "Java Test(JUnit5)"
