
version: 1.0.{build}

notifications:
  - provider: Email
    to:
      - luncliff@gmail.com

branches:
  except:
    - gh-pages
    - docs

shallow_clone: true
clone_depth: 1

image:
  - Visual Studio 2019

platform:
  - x64
  # - x86

configuration:
  - Debug
  # - Release

environment:
  global:
    install_path: C:/install
  matrix:
    - image: Visual Studio 2019
      Qt5_DIR: "C:/Qt/5.15/msvc2019_64/lib/cmake/Qt5"
    - image: Visual Studio 2017
      Qt5_DIR: "C:/Qt/5.12/msvc2017_64/lib/cmake/Qt5"
    - image: Visual Studio 2019

cache:
  - C:/tools/vcpkg/installed

install:
  - ps: tree /F "$env:Qt5_DIR"
  - ps: if($env:PLATFORM -eq "x64"){ $env:VCPKG_TARGET_TRIPLET="x64-windows" }
  - ps: if($env:PLATFORM -eq "x86"){ $env:VCPKG_TARGET_TRIPLET="x86-windows" }
  - ps: |
      vcpkg install --triplet $env:VCPKG_TARGET_TRIPLET `
        ms-gsl spdlog catch2 glfw3 tinygltf directxtex directxtk glslang glm
  - ps: |
      if( "$env:Qt5_DIR" -eq "" ){ vcpkg install --triplet $env:VCPKG_TARGET_TRIPLET `
        angle `
      }
  - ps: vcpkg list

before_build:
  - ps: if($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017"){ $env:GENERATOR="Visual Studio 15 2017" }
  - ps: if($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019"){ $env:GENERATOR="Visual Studio 16 2019" }
  - ps: if($env:PLATFORM -eq "x86"){ $env:PLATFORM="Win32" }
  - ps: |
      cmake . -G "$env:GENERATOR" -DBUILD_SHARED_LIBS=true `
        -DCMAKE_BUILD_TYPE="$env:CONFIGURATION" `
        -DCMAKE_INSTALL_PREFIX="$env:INSTALL_PATH" `
        -DCMAKE_TOOLCHAIN_FILE="C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="$env:VCPKG_TARGET_TRIPLET" `
        -DVCPKG_TARGET_TRIPLET="$env:VCPKG_TARGET_TRIPLET" `
        -DQt5_DIR="$env:Qt5_DIR"

build:
  project: graphics.sln
  verbosity: minimal

test_script:
  # - ps: if($env:CONFIGURATION -eq "Debug"){   $env:PATH="$env:PATH;c:/tools/vcpkg/installed/$env:VCPKG_TARGET_TRIPLET/debug/bin" }
  # - ps: if($env:CONFIGURATION -eq "Release"){ $env:PATH="$env:PATH;c:/tools/vcpkg/installed/$env:VCPKG_TARGET_TRIPLET/bin" }
  - ps: ctest --verbose -C "$env:CONFIGURATION"
