version: 1.0.{build}

notifications:
  - provider: Email
    to:
      - luncliff@gmail.com

branches:
  except:
    - gh-pages
    - docs

shallow_clone: true
clone_depth: 1

image:
  - Visual Studio 2019

platform:
  - x64
  # - x86

configuration:
  - Debug
  - Release

# $env:Qt5_DIR makes the project configures with QtANGLE
environment:
  global:
    install_path: C:/install
  matrix:
    - image: Visual Studio 2019
      Qt5_DIR: "C:/Qt/5.15/msvc2019_64/lib/cmake/Qt5"
    - image: Visual Studio 2017
      Qt5_DIR: "C:/Qt/5.12/msvc2017_64/lib/cmake/Qt5"
    - image: Visual Studio 2017
      Qt5_DIR: "C:/Qt/5.9/msvc2017_64/lib/cmake/Qt5"
    - image: Visual Studio 2019

cache:
  - C:/tools/vcpkg/installed

install:
  - ps: tree /F "$env:Qt5_DIR"
  - ps: if($env:PLATFORM -eq "x64"){ $env:VCPKG_TARGET_TRIPLET="x64-windows" }
  - ps: if($env:PLATFORM -eq "x86"){ $env:VCPKG_TARGET_TRIPLET="x86-windows" }
  - ps: |
      vcpkg install --triplet $env:VCPKG_TARGET_TRIPLET `
        ms-gsl spdlog catch2 glfw3 tinygltf directxmath directx-headers directxtex directxtk
  - ps: |
      if( "$env:Qt5_DIR" -eq "" ){ vcpkg install --triplet $env:VCPKG_TARGET_TRIPLET `
        angle `
      }
  - ps: vcpkg list

before_build:
  - ps: if($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017"){ $env:GENERATOR="Visual Studio 15 2017" }
  - ps: if($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019"){ $env:GENERATOR="Visual Studio 16 2019" }
  - ps: if($env:PLATFORM -eq "x86"){ $env:PLATFORM="Win32" }
  - ps: |
      New-Item -Name build -Type Directory
      Push-Location build
      cmake .. -G "$env:GENERATOR" -DBUILD_SHARED_LIBS=true `
        -DCMAKE_BUILD_TYPE="$env:CONFIGURATION" `
        -DCMAKE_INSTALL_PREFIX="$env:INSTALL_PATH" `
        -DCMAKE_TOOLCHAIN_FILE="C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="$env:VCPKG_TARGET_TRIPLET" `
        -DCMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION="10.0.18362.0"
      Pop-Location

build:
  project: build/graphics.sln
  # verbosity: minimal

before_test:
  - ps: if($env:CONFIGURATION -eq "Debug"){   $env:PATH="$env:PATH;c:/tools/vcpkg/installed/$env:VCPKG_TARGET_TRIPLET/debug/bin" }
  - ps: if($env:CONFIGURATION -eq "Release"){ $env:PATH="$env:PATH;c:/tools/vcpkg/installed/$env:VCPKG_TARGET_TRIPLET/bin" }
  - ps: Push-Location "build/$env:CONFIGURATION"
  - ps: Get-Location

test_script:
  # - ps: ./graphics_test_suite.exe --reporter sonarqube --out sonarqube.xml
  - ps: ./graphics_test_suite.exe

after_test:
  - ps: Pop-Location
